# Generated by Django 4.2.4 on 2023-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedimage_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], max_length=10),
        ),
    ]
