# Generated by Django 4.2.4 on 2023-08-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_email_profile_name_profile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
