# Generated by Django 4.2.4 on 2023-08-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
