# Generated by Django 4.2.4 on 2023-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
